### ISSUE TITLE
Sim fails to start with AttributeError since 3131ff8

### ISSUE THREAD

**Issue by GeorgeEbberson** [emfcamp/badge-2024-software#306]
**Describe the bug**
Since 3131ff8, the simulator fails with `AttributeError: module 'neopixel' has no attribute 'DimCorrection'`. Testing one commit earlier (bb55fc5) it works as expected and the simulator starts.

Full startup log of the error:
```
pygame 2.6.1 (SDL 2.28.4, Python 3.10.20)
Hello from the pygame community. https://www.pygame.org/contribute.html
Warning: `mad` is missing, MP3 support in `media` mock will be limited
Using /tmp/sim as /flash mount
Info: No custom config.py found
Info: No custom button mapping found in config.py
Registered async event handler for RequestForegroundPushEvent: _Scheduler - _handle_request_foreground_push
Registered async event handler for RequestForegroundPopEvent: _Scheduler - _handle_request_foreground_pop
Registered async event handler for RequestStartAppEvent: _Scheduler - _handle_start_app
Registered async event handler for RequestStopAppEvent: _Scheduler - _handle_stop_app
('None', None)
Registered async event handler for HexpansionInsertionEvent: HexpansionManagerApp - handle_hexpansion_insertion
Registered async event handler for HexpansionRemovalEvent: HexpansionManagerApp - handle_hexpansion_removal
Registered event handler for ButtonDownEvent: HexpansionManagerApp - handle_button_down
Registered event handler for ButtonUpEvent: HexpansionManagerApp - handle_button_up
Registered async event handler for PatternEnable: PatternDisplay - _enable
Registered async event handler for PatternDisable: PatternDisplay - _disable
Registered async event handler for PatternReload: PatternDisplay - _reload
Registered async event handler for PatternSet: PatternDisplay - _set
('rainbow', None)
Loading pattern: rainbow
Traceback (most recent call last):
  File "/mnt/d/dev/badge-2024-software/sim/run.py", line 200, in <module>
    sim_main()
  File "/mnt/d/dev/badge-2024-software/sim/run.py", line 196, in sim_main
    import main
  File "/mnt/d/dev/badge-2024-software/modules/main.py", line 23, in <module>
    scheduler.start_app(PatternDisplay())
  File "/mnt/d/dev/badge-2024-software/modules/system/patterndisplay/app.py", line 29, in __init__
    self.correction = neopixel.DimCorrection(1.0)
AttributeError: module 'neopixel' has no attribute 'DimCorrection'
```

Version: 3131ff8 on branch main

**To Reproduce**

1. Checkout 3131ff8 or later
2. cd sim
3. pipenv run python run.py

**Expected behavior**
Simulator starts and runs normally
